### ISSUE TITLE
[Bug]: Apache configuration missing

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/skeleton#105]
### Expected behavior

The Documentation page links to the public/.htaccess file in the skeleton, this has been deleted.

https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Apache_Configuration.html

### Actual behavior

Link is broken, file is missing now.

Please provide documentation on how to set up Pimcore with apache, not everybody is using nginx.

### Steps to reproduce

Click link in docs.

**Comment by jdreesen** [comment]
The Apache configuration can be found here: https://pimcore.com/docs/pimcore/10.5/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Apache_Configuration.html

**Comment by HaaseIT** [comment]
So, we have a timing problem here I guess.

**Comment by jdreesen** [comment]
Right, the skeleton is being prepared for Pimcore 10.5.

**Comment by jdreesen** [comment]
I sent a PR to fix the link in the current docs: pimcore/pimcore#12658

**Comment by brusch** [comment]
Updated the docs https://github.com/pimcore/pimcore/commit/5437ac186db0af1e2f4e14b3ceb7d91b9a49035e
