### ISSUE TITLE
[Bug]: Skeleton now requires unstable pimcore version

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/skeleton#106]
### Expected behavior

Pimcore-Skeleton requires a stable Pimcore version in composer.json

### Actual behavior

Pimcore-Skeleton requires an unstable Pimcore version in composer.json (10.x-dev)

Is the pimcore Skeleton not meant to be the starting point for new installations? If not, what is the replacement?

### Steps to reproduce

Look into composer.json

**Comment by jdreesen** [comment]
It is, but I think you should use a release: https://github.com/pimcore/skeleton/releases

**Comment by dvesh3** [comment]
We have 2 branches now, `release branch` e.g. 10.1 (for tagging the bugfix releases) which still requires Pimcore stable version and `main branch` e.g. 10.x (for master changes) which requires 10.x-dev for running tests with latest changes on pimcore/pimcore. 

If you look at the latest stable version it requires correct Pimcore version https://github.com/pimcore/skeleton/blob/v10.1.13/composer.json#L11

**Comment by HaaseIT** [comment]
Good to know, ist this documented in the setup instructions?

**Comment by dvesh3** [comment]
I don't think there's a need for that since `composer create-project pimcore/skeleton my-project` still installs the stable version until unless you request for 10.x version.

**Comment by HaaseIT** [comment]
I have a fork of the skeleton in which I added Symfony Encore along with some other Bundles like nelmio/security-bundle.

This is currently based on the 10.x branch. So, should I switch this to the release branch then?

**Comment by dvesh3** [comment]
If you are using the fork in a project, then it is recommended to switch to release branch to have a stable version.

**Comment by HaaseIT** [comment]
Yeah, this is my starting point for new implementations. Will use the release branch then, thanks.

**Comment by dvesh3** [comment]
> I don't think there's a need for that since `composer create-project pimcore/skeleton my-project` still installs the stable version until unless you request for 10.x version.

I got your point about documenting this change as before there was just 10.x branch for stable releases and now there's a release branch. Maybe we can add a note in the [README.md](https://github.com/pimcore/skeleton/blob/10.x/README.md)
