### ISSUE TITLE
[Improvement]: Permissions "var/log/dev.log"

### ISSUE THREAD

**Issue by horeca2** [pimcore/skeleton#139]
### Improvement description

After some time of server operation after start, the owner and group of the file "var/log/dev.log" changes to "root". As a result, I get the error "failed to open stream: Permission denied". If I manually change the owner and group, then everything works again for a while, but then it fails again

How to solve this problem?
![2023-03-11_22-05-43](https://user-images.githubusercontent.com/56235433/224507132-d75773d9-2e67-4f96-adad-3c7aa6aac5e0.png)
![2023-03-11_22-09-57](https://user-images.githubusercontent.com/56235433/224507222-84e9b2a8-3493-4835-bd63-b9adcf219df3.png)

**Comment by horeca2** [comment]
I guess when the file gets too big it gets deleted and re-created with the wrong permissions. How to fix it?

**Comment by solverat** [comment]
Maybe your cron task is running with a wrong user?

**Comment by horeca2** [comment]
> Maybe your cron task is running with a wrong user?

You are right, the error appeared after I installed the Data Importer and configured its cron jobs. Thank you for your help
