### ISSUE TITLE
[Bug]: Docker install fails in different ways

### ISSUE THREAD

**Issue by bachi76** [pimcore/skeleton#143]
### Expected behavior

Following the docker setup instructions on https://github.com/pimcore/skeleton I would expect the setup to be smooth and quick.

### Actual behavior

When I use the commands as stated, using 

`pimcore/pimcore image docker run -u `id -u`:`id -g` --rm -v `pwd`:/var/www/html pimcore/pimcore:php8.2-latest composer create-project pimcore/skeleton my-project`

I get:

> pimcore-camunda-supervisord-1  | Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.14. in /var/www/html/vendor/composer/platform_check.php on line 24

Same error when subsequently trying `docker compose exec php vendor/bin/pimcore-install`

When I then try `pimcore/pimcore image docker run -u `id -u`:`id -g` --rm -v `pwd`:/var/www/html pimcore/pimcore:php8.1-latest composer create-project pimcore/skeleton my-project` (8.1 instead of 8.2) I get to the pimcore setup. After entering values, I get

> Starting the install process...
> 
>   0/11 [>---------------------------]   0%
>                                                                              
>  [ERROR] The following errors were encountered during installation                                                      
>                                                                                                                         
>  * Couldn't establish connection to MySQL: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
> 

The db container is running just fine:

> NAME                            COMMAND                  SERVICE             STATUS              PORTS
> pimcore-camunda-db-1            "docker-entrypoint.s…"   db                  running             3306/tcp

What gives? Is this setup still maintained? I expected this to be a breeze.

### Steps to reproduce

just follow your instructions on https://github.com/pimcore/skeleton -> Docker

**Comment by brusch** [comment]
Yeah, this is still maintained and supported, actually for me it works just fine. 
Can you please share the exact commands you ran? So that we can reproduce the issue? Thanks!

**Comment by bachi76** [comment]
Ok, interesting. I literally copy/pasted the commands from that page.

`docker run -u `id -u`:`id -g` --rm -v `pwd`:/var/www/html pimcore/pimcore:php8.2-latest composer create-project pimcore/skeleton test`

Creating a "pimcore/skeleton" project at "./test"
Cannot create cache directory /.cache/composer/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only.

 [OK] All assets were successfully installed. 
 
 `docker compose up -d`
 
When I look into the docker compose logs, I see already this:

> test-supervisord-1  | Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.14. in /var/www/html/vendor/composer/platform_check.php on line 24

 When I log into the php container and print the php version, I get:
 
 `docker compose exec -it php bash`
 
>  I have no name!@32f5ea708e71:/var/www/html$ php --version
> PHP 8.1.14 (cli) (built: Jan 11 2023 07:57:04) (NTS)

 What am I doing wrong?

**Comment by jkovacevic992** [comment]
Follow the readme. instead of running:
`docker compose exec php vendor/bin/pimcore-install`
try:
`docker-compose exec php vendor/bin/pimcore-install --mysql-host-socket=db --mysql-username=pimcore --mysql-password=pimcore --mysql-database=pimcore`

Regarding the `docker-compose up -d `issue, 
open your project's docker-compose.yaml and edit this part:
```
php:
        user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:php8.1-debug-latest
```
change it to:
```
php:
        user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:php8.2-latest
```

**Comment by brusch** [comment]
The reason is that https://github.com/pimcore/skeleton is pointing already to the v11 instructions, use https://github.com/pimcore/skeleton/tree/10.2 for Pimcore 10.

This situation will be solved as soon as v11 is released (very soon 😉 )
