### ISSUE TITLE
PHP7.4?

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/skeleton#15]
@brusch did you create the composer.lock with PHP7.4? 

https://github.com/pimcore/skeleton/blob/master/composer.lock#L3245

Currently the skeleton only install with 7.4...

**Comment by brusch** [comment]
Oh dear, wasn't aware this will cause issues. Will recreate it asap. Thanks!

**Comment by brusch** [comment]
latest release built with PHP 7.2, should be ok again
