### ISSUE TITLE
[Bug]: Admin panel does not work

### ISSUE THREAD

**Issue by betterapp** [pimcore/skeleton#160]
### Expected behavior

Admin panel is working

### Actual behavior

Not Found
The requested URL was not found on this server.

### Steps to reproduce

1. Install PimCore 11 with composer on local machine on pimcore11.pim domain
2. run /vendor/bin/pimcore-install
3. everything is ok
4. go to http://pimcore11.pim -> I see PimCore logo
5. go to http://pimcore11.pim/admin and I see

Not Found
The requested URL was not found on this server.

As I see there is no any .htaccess file in /public directory. Is it ok ?

**Comment by kingjia90** [comment]
Are you on Apache? If yes, then you may need to re-add the `htaccess` file. It doesn't come by default with the skeleton anymore
See also https://github.com/pimcore/skeleton/pull/101

**Comment by dvesh3** [comment]
Docs here https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Apache_Configuration.html
