### ISSUE TITLE
[Feature]: Skeleton Repository for SAAS application

### ISSUE THREAD

**Issue by kaurov** [pimcore/skeleton#168]
### Feature description

Can you please create one more repository for Skeleton of the SAAS application.
It will promote Pimcore for many Startups to be used as 1st step for MVP.

Required features that I believe are necessary to be added to existing ones that you can fork from current Skeleton:
* documents already editable
* layout
* customers and personalization bundles activated
* users/tenants registration + login including League/oauth2-client
* users password recovery page
* subscription tariffs selection:
* * free
* * small
* * middle
* * big
* recurring payments
* PHP service allowing payment gateway injection
* customer profile page where he can edit his personal data and tariff and payment data
* Impressum and Public Offer pages samples
* Documents skeletons for: page for legged in user, page for paid user
* post-merge.sh script to apply migrations and rebuild classes after code is pulled
* pre-push.sh script to execute all checks of PHP code before to push it
* to put this functionality in the bundle, so multiple startups can load updates using composer instead of hard-coding files on the beginning only.
* ? balance state, deposit balance pages

**Comment by alexej-d** [comment]
I would suggest you check out Pimcore's demo project. A skeleton is the bare minimum to run Pimcore.

**Comment by fashxp** [comment]
we don't plan to do that.
