### ISSUE TITLE
[Improvement]: Use port 3307 instead of 3306 in docker-compose.yaml

### ISSUE THREAD

**Issue by kaurov** [pimcore/skeleton#178]
### Improvement description

I believe many developers (including me) have localhost web server installed and use port 3306 for local MySQL.
Please use port 3307 in docker-compose.yml and other configs to avoid WSL conflicts with MySQL.
For both repositories, Skeleton and Demo.

**Comment by jdreesen** [comment]
The skeleton currently doesn't expose the database port at all. If you want to expose it, you have to configure it yourself and can use any value that suits you. Same for the demo.
