### ISSUE TITLE
Please update codeception

### ISSUE THREAD

**Issue by campino2k** [pimcore/skeleton#18]
https://github.com/pimcore/skeleton/blob/873d9f7cd7bbd33f2797e84bde6c56e86cba070b/composer.json#L16

The version of codeception uses facebook/webdriver, which has been replaced by php-webdriver/webdriver.

Since projects like "symfony/panther" and other tools using webdriver use the php-webdriver version composer update and install will fail.

Reproduce: create pimcore project, add symfony/panther as requirement. If this works, `composer update` will break.

**Comment by dpfaffenbauer** [comment]
Since it is just a skeleton, you can change it for yourself anyway... but yes, easier if the skeleton already supports it.

**Comment by brusch** [comment]
@campino2k see https://github.com/pimcore/pimcore/issues/5827 - unfortunately we have to stay on the current version until we finally drop Symfony 3.4 support.
