### ISSUE TITLE
Download csv assets does not work

### ISSUE THREAD

**Issue by fashxp** [pimcore/skeleton#192]
Hi everyone,

I'm currently working on a project using Pimcore, and I've encountered an issue with downloading .csv files from the Digital Asset Management (DAM) system using the public URL.

When I try to access the .csv file through its public URL, I get the following error:
No route found for "GET http://localhost:2009/route-name/name-file.csv"

Interestingly, when I use an .xlsx format, the download works correctly, but the .csv files do not. Unfortunately, I require the files to be in .csv format.

_Originally posted by @AlephCode in https://github.com/pimcore/pimcore/discussions/17066_

**Comment by alexz707** [comment]
added config to demo, ee demo and skeleton
