### ISSUE TITLE
[Bug]: Bundle missing: translations-provider-interfaces

### ISSUE THREAD

**Issue by emiljlynge** [pimcore/skeleton#210]
### Expected behavior

Successful bundle installation

### Actual behavior

The bundle cannot be installed.

### Steps to reproduce

Install Pimcore (v11.4.1)
Try to install the translation_provider_interfaces bundle as described [here](https://pimcore.com/docs/platform/Translation_Provider_Interfaces/Installation_and_Configuration/).

**Comment by fashxp** [comment]
it is an enterprise extension, you need to buy the enterprise subscription first.
