### ISSUE TITLE
Customview "Where" condition not working - 6.3.1

### ISSUE THREAD

**Issue by baladpi** [pimcore/skeleton#26]
“treetype” => “object”,
“name” => “Sample”,
“icon” => “/bundles/pimcoreadmin/img/flat-white-icons/pimcore-main-icon-product.svg”,
“id” => 2,
“rootfolder” => “/”,
“showroot” => FALSE,
“classes” => “42,13,34”,
“position” => “left”,
“sort” => “5”,
“expanded” => false,
“where” => “o_key LIKE ‘/Productmap/%’”,

I want here to create a perspective in which display the objects which satisfy the where condition, but if I remove the where condition, its showing object (all object), but i want to use where condition, because, i want to display only objects from specfic folders.

**Comment by fashxp** [comment]
cannot be reproduced, where filter works as expected. 

please check your where condition ... `o_key` never has '/' characters, most probably you want to use `o_path`

**Comment by fashxp** [comment]
please use our forum or gitter chat for further support.

**Comment by baladpi** [comment]
Yes… My post was wrong, but I tried with “o_path LIKE ‘/Productmap/%’” only… not working

**Comment by baladpi** [comment]
I updated to 6.3.6, but same issue.. not working

**Comment by baladpi** [comment]
where condition is working with o_type but not with o_path

**Comment by fashxp** [comment]
if there is a problem, please create a reproducible case on our demo application and make an issue at the [pimcore repository](https://github.com/pimcore/pimcore) - or even better, provide a PR to fix it. 
Thank you.

**Comment by dvesh3** [comment]
@baladpi if you are able to create a reproducible case then just post it here. We'll reopen and move this ticket to Pimcore ;)

**Comment by baladpi** [comment]
Here, in “where” condition, if I user o_id >= 12, then the output is correct,
(e.g) will get folder_name4,folder_name6, folder_name7 and and folder_name8 and object also which has the ID > 12.

But if I use o_path LIKE “%folder_name5%” OR o_path LIKE “%folder_name7%”, the output is empty
![cropped](https://user-images.githubusercontent.com/8745583/82113325-d000ca00-9772-11ea-8e66-d0e73f48fd5e.jpg)

**Comment by fashxp** [comment]
where condition is applied to every folder hierarchy ... so if in first level no folder matches your condition, no folders will be shown.
please use our forums and/or gitter for further support...
