### ISSUE TITLE
403 Not Authorized error when launching https://localhost/admin in firefox browser

### ISSUE THREAD

**Issue by Giuscar** [pimcore/skeleton#34]
Hello, 

I have an issue in launching the project in localhost. I have some unauthorized accesses when I try to open the pimcore backoffice. 
In the following picture you can some of the gets which are generating 403 not authorized error: 
![image](https://user-images.githubusercontent.com/24507440/96260640-95b88480-0fbf-11eb-9d78-98087a92b81b.png)

These are the logs I've retrieved from apache set up in one of your docker containers (pimcore-php)

![image](https://user-images.githubusercontent.com/24507440/96260539-76215c00-0fbf-11eb-83e0-56b8b91ed487.png)

Can you please help me with this issue? 

Thanks a lot.

**Comment by brusch** [comment]
https://talk.pimcore.org/
https://gitter.im/pimcore/pimcore
