### ISSUE TITLE
Error while comparing document versions

### ISSUE THREAD

**Issue by pimcore-sg** [pimcore/skeleton#4]
Getting below error while comparing document versions:- 

> The template "PimcoreAdminBundle:Admin/Document:diff-versions-unsupported.html.php" does not exist.

I have investigated the same and found these files are available in wrong directory. Please review the attached screenshots.

![screenshot-pim local com-2019 02 25-19-59-38](https://user-images.githubusercontent.com/47360708/53344582-04ebeb80-3939-11e9-9b5b-2828d59f2f9f.png)

![screenshot 2019-02-25 at 8 06 37 pm](https://user-images.githubusercontent.com/47360708/53344561-f8679300-3938-11e9-9032-68bcf340b1ef.png)

**Comment by brusch** [comment]
1. This is the wrong place to report issues for Pimcore, see: https://github.com/pimcore/pimcore 😉
2. The problem was already fixed, see: https://github.com/pimcore/pimcore/issues/3504
