### ISSUE TITLE
Can't download "pimcore/pimcore:2.8.10" 

### ISSUE THREAD

**Issue by GaneshKandu** [pimcore/skeleton#44]
Hi,

I am trying to install ``pimcore/skeleton`` with latest ``pimcore/pimcore : 2.8.10`` package.
but i am getting is ``pimcore/pimcore : 2.8.9``

you need to update ``pimcore/skeleton`` package on packagist.org.

**Comment by brusch** [comment]
It's there: 
https://packagist.org/packages/pimcore/skeleton - latest is `2.8.12` which installs smoothly.

**Comment by GaneshKandu** [comment]
Edited
i mean ``pimcore/pimcore : 6.8.10``

**Comment by brusch** [comment]
Thanks for clarifying 😉 Done

**Comment by GaneshKandu** [comment]
Thanks ! :+1:
