### ISSUE TITLE
skeleton does not work with php 8

### ISSUE THREAD

**Issue by frithjof** [pimcore/skeleton#45]
- Installation request for doctrine/dbal 2.10.4 -> satisfiable by doctrine/dbal[2.10.4].
    - doctrine/dbal 2.10.4 requires php ^7.2 -> your PHP version (8.0.3) does not satisfy that requirement.

and a lot more

this feels strange combined with the reference to the php8 docker container

so probably it should be better to still include the php7.4 container

**Comment by antoinich** [comment]
Same here

**Comment by brusch** [comment]
Pimcore 6 doesn't work with PHP 8.
Pimcore 10 will do.

**Comment by cmann90** [comment]
Then why does the docker-compose.yml of the repository define PHP8.0 for the release?
5985b8db9c3e4ff7b5c590cea6cc39a7a01ae95c

Shouldn't a release work out of the box?
Why not use a dev branch instead?

**Comment by jdreesen** [comment]
In the stable branch it's PHP 7.4: https://github.com/pimcore/skeleton/blob/2.8/docker-compose.yml

`master` is unreleased yet and in preparation for Pimcore 10.
