### ISSUE TITLE
Error creating link under HOME.

### ISSUE THREAD

**Issue by RolandoPer** [pimcore/skeleton#47]
Hi,
After creating a LINK item, the document tree is not displayed. I get this on the console:
`
Error: You're trying to decode an invalid JSON String: {"offset":0,"limit":50,"total":"1","nodes":[{"id":2,"idx":1,"text":"es_PE","type":"link","path":"\/es_PE","basePath":"\/","locked":false,"lockOwner":false,"published":true,"elementType":"document","leaf":false,"permissions":{"view":true,"remove":true,"settings":true,"rename":true,"publish":true,"unpublish":true,"create":true},"expandable":false,"loaded":true,"expanded":true,"icon":null,"iconCls":"pimcore_icon_link","cls":"","qtipCfg":{"title":"ID: 2","text":"Type: link"}}],"filter":"","inSearch":0}{"success":false,"message":"Serialization of \u0027Doctrine\\DBAL\\Driver\\PDOConnection\u0027 is not allowed","trace":[{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Profiler\/FileProfilerStorage.php","line":175,"function":"serialize","args":[{"token":"51a178","parent":null,"children":[],"data":{"pimcore":{},"request":{},"time":{},"memory":{},"validator":{},"ajax":{},"pimcore_targeting":{},"form":{},"exception":{},"logger":{},"events":{},"router":{},"cache":{},"translation":{},"security":{},"twig":{},"db":{},"swiftmailer":{},"dump":{},"config":{}},"ip":"172.17.0.1","method":"GET","url":"http:\/\/localhost:9003\/admin\/document\/tree-get-childs-by-id?_dc=1617774295411\u0026limit=50\u0026node=1\u0026view=","time":1617774295,"status_code":200}]},{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Profiler\/Profiler.php","line":104,"function":"write","class":"Symfony\\Component\\HttpKernel\\Profiler\\FileProfilerStorage","type":"-\u003E","args":[{}]},{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/EventListener\/ProfilerListener.php","line":112,"function":"saveProfile","class":"Symfony\\Component\\HttpKernel\\Profiler\\Profiler","type":"-\u003E","args":[{}]},{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/Debug\/WrappedListener.php","line":126,"function":"onKernelTerminate","class":"Symfony\\Component\\HttpKernel\\EventListener\\ProfilerListener","type":"-\u003E","args":[{},"kernel.terminate",{}]},{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php","line":264,"function":"__invoke","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"-\u003E","args":[{},"kernel.terminate",{}]},{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","args":[[{},{}],"kernel.terminate",{}]},{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","args":[[{},{}],"kernel.terminate",{}]},{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/Debug\/TraceableEventDispatcher.php","line":168,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","args":[{},"kernel.terminate"]},{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php","line":100,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"-\u003E","args":[{},"kernel.terminate"]},{"file":"\/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Kernel.php","line":166,"function":"terminate","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},{"headers":{}}]},{"file":"\/var\/www\/html\/web\/app.php","line":38,"function":"terminate","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},{"headers":{}}]}],"traceString":"in \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Profiler\/FileProfilerStorage.php:175\n#0 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Profiler\/FileProfilerStorage.php(175): serialize(Array)\n#1 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Profiler\/Profiler.php(104): Symfony\\Component\\HttpKernel\\Profiler\\FileProfilerStorage-\u003Ewrite(Object(Symfony\\Component\\HttpKernel\\Profiler\\Profile))\n#2 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/EventListener\/ProfilerListener.php(112): Symfony\\Component\\HttpKernel\\Profiler\\Profiler-\u003EsaveProfile(Object(Symfony\\Component\\HttpKernel\\Profiler\\Profile))\n#3 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/Debug\/WrappedListener.php(126): Symfony\\Component\\HttpKernel\\EventListener\\ProfilerListener-\u003EonKernelTerminate(Object(Symfony\\Component\\HttpKernel\\Event\\TerminateEvent), \u0027kernel.terminat...\u0027, Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#4 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php(264): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener-\u003E__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\TerminateEvent), \u0027kernel.terminat...\u0027, Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#5 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher-\u003EdoDispatch(Array, \u0027kernel.terminat...\u0027, Object(Symfony\\Component\\HttpKernel\\Event\\TerminateEvent))\n#6 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher-\u003EcallListeners(Array, \u0027kernel.terminat...\u0027, Object(Symfony\\Component\\HttpKernel\\Event\\TerminateEvent))\n#7 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/EventDispatcher\/Debug\/TraceableEventDispatcher.php(168): Symfony\\Component\\EventDispatcher\\EventDispatcher-\u003Edispatch(Object(Symfony\\Component\\HttpKernel\\Event\\TerminateEvent), \u0027kernel.terminat...\u0027)\n#8 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php(100): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher-\u003Edispatch(Object(Symfony\\Component\\HttpKernel\\Event\\TerminateEvent), \u0027kernel.terminat...\u0027)\n#9 \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Kernel.php(166): Symfony\\Component\\HttpKernel\\HttpKernel-\u003Eterminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Pimcore\\Bundle\\AdminBundle\\HttpFoundation\\JsonResponse))\n#10 \/var\/www\/html\/web\/app.php(38): Symfony\\Component\\HttpKernel\\Kernel-\u003Eterminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Pimcore\\Bundle\\AdminBundle\\HttpFoundation\\JsonResponse))\n#11 {main}"}<br />
<b>Fatal error</b>:  Uncaught BadMethodCallException: Symfony\Component\VarDumper\Cloner\Data objects are immutable. in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/Data.php:165
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/EventDataCollector.php(88): Symfony\Component\VarDumper\Cloner\Data-&gt;offsetSet('called_listener...', Array)
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/EventDataCollector.php(68): Symfony\Component\HttpKernel\DataCollector\EventDataCollector-&gt;setCalledListeners(Array)
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php(100): Symfony\Component\HttpKernel\DataCollector\EventDataCollector-&gt;lateCollect()
#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php(112): Symfony\Component\HttpKernel\Profiler\Profiler-&gt;saveProfile(Object(Symfony\Component\HttpKernel\Profiler\Profile))
#4 /var/www/html/ in <b>/var/www/html/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/Data.php</b> on line <b>165</b><br />
`
![imagen](https://user-images.githubusercontent.com/1970975/113818219-19685800-973d-11eb-9656-81c74bf6997a.png)

I'm using:
Pimcore Skeleton v.2.8.16
PHP 7.4.16
MariaDB 10.4

Any suggestion?. Thanks

**Comment by brusch** [comment]
See https://github.com/pimcore/pimcore/pull/8696 
Can you please confirm this fixed your issue? Thanks a lot!

**Comment by RolandoPer** [comment]
This solves the issue. Thank you.
