### ISSUE TITLE
Don't make SymLinksIfOwnerMatch active by default.

### ISSUE THREAD

**Issue by Yivan** [pimcore/skeleton#5]
Hello,

In the .htaccess, there is `Options +SymLinksIfOwnerMatch` (please see: https://github.com/pimcore/skeleton/blob/master/web/.htaccess#L25).

On some environment, ACL linux permissions is used, so owner is not www-data (apache), but with ACL www-data has rwx owner/group permissions.
SymLinksIfOwnerMatch don't allow ww-data (apache) to follow symlink in this case (even if it has ACL rwx permissions as owner).

I think it should not be enabled by default. I know it is enabled for security, but maybe it could be just commented by default in the htaccess. So people wanted to enforce it can decomment it.
**Any ways this option should be setted by the admin in the virtualhost in any serious security scheme** (not in the htaccess, delegating the security to the developpers ; )).

In our case, in our local environnement we use ACL because www-data is not the user. It allow to git pull as the user but ACL give rwx to www-data as owner/group. But symlink are not followed by apache with this default activated option. So we need to adapt htaccess to each project...

Hope it make sense.
Thanks.

**Comment by brusch** [comment]
I'd say your case is an edge case and we should follow security first.
