### ISSUE TITLE
Frontend is not working properly when running with Docker

### ISSUE THREAD

**Issue by zkokelj** [pimcore/skeleton#55]
Hi, I followed [this](https://github.com/pimcore/skeleton) readme for Docker installation. Everything finished without any errors, but when I open `localhost` or `localhost/admin` it seems that all the css styles, images, etc. are missing.

Link to an image (screenshot): [https://ibb.co/G28krSk](https://ibb.co/G28krSk).
Does anyone know hot to solve this issue? 

I am using Ubuntu 20.04 & Docker version 20.10.2

**Comment by VeiJar1** [comment]
I have the same problem.

**Comment by dpfaffenbauer** [comment]
On Linux: Map your user to the www-data user within the container.
On Mac/Windows: Run `chown -R www-data: .` within the container.

**Comment by dvesh3** [comment]
Closed due to inactivity. We can re-open the issue, if the problem persists.
