### ISSUE TITLE
[Bug]: Docker setup not installable

### ISSUE THREAD

**Issue by foxgreek** [pimcore/skeleton#65]
### Expected behavior

After running **composer-create** I do expect pimcore installs itself with the **vendor/bin/pimcore-install** command.

### Actual behavior

pimcore can't find db while installing:

![image](https://user-images.githubusercontent.com/40141606/135423285-e8fae8a0-3f85-4ae8-aa81-ec2652d85cfe.png)

### Steps to reproduce

Run the Docker setup as mentioned in README:
```
COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/skeleton my-project
cd ./my-project
docker-compose run --rm php-fpm vendor/bin/pimcore-install --mysql-host-socket=db --mysql-username=pimcore --mysql-password=pimcore --mysql-database=pimcore
```

**Comment by foxgreek** [comment]
@brusch - sorry still not working

**Comment by brusch** [comment]
Just tried it step by step, worked. Just follow the updated steps.

**Comment by foxgreek** [comment]
Thanks a lot! Had to remove the old containers ...
