### ISSUE TITLE
composer.lock is in .gitignore

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/skeleton#7]
It is common practice to add composer.lock to version control to be able to install the same library versions on different systems (e.g. live and local development). Why is it in .gitignore?

**Comment by podarcis** [comment]
I agree, composer.lock should be committed to SCM. https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

And I'm not sure about the meaning of .gitignore's [first line](https://github.com/pimcore/skeleton/blob/master/.gitignore#L1) ```# remove the following ignores for your project```.

**Comment by dpfaffenbauer** [comment]
guess this can be closed? Pimcore already removed the composer.lock gitignore and also added a composer.lock file to the skeleton
