### ISSUE TITLE
[Bug]: config/config.yaml is not being loaded

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/skeleton#73]
### Expected behavior

Since it exists, `config/config.yaml` should be loaded by something.

### Actual behavior

`config/config.yaml` is not actually loaded by anything.

### Steps to reproduce

Create a new project from Skeleton, try to rely on `config/config.yaml` for some general config.

**Comment by paulverdu** [comment]
Having the same problem

**Comment by jdreesen** [comment]
[`config/config.yaml`](https://github.com/pimcore/skeleton/blob/10.x/config/config.yaml) gets loaded through imports in [`config/packages/dev/config.yaml`](https://github.com/pimcore/skeleton/blob/10.x/config/packages/dev/config.yaml), [`config/packages/prod/config.yaml`](https://github.com/pimcore/skeleton/blob/10.x/config/packages/prod/config.yaml) or [`config/packages/test/config.yaml`](https://github.com/pimcore/skeleton/blob/10.x/config/packages/test/config.yaml) (depending on your environment), which themselves get loaded in the [Kernel](https://github.com/pimcore/pimcore/blob/9d82ae1a5c5806406344d75445b3d3a1f8adb47e/lib/Kernel.php#L121).

**Comment by brusch** [comment]
@jdreesen thanks for clarifying!
