### ISSUE TITLE
Follow symfony 4 catalogs structure

### ISSUE THREAD

**Issue by mbolka** [pimcore/skeleton#9]
Pimcore has moved from 5.x to 6.x and switched into Symfony 4.x. I think we should start using Symfony 4 catalogs structure:
/config instead of /app/config
/public instead of /web
index.php instead of app.php

**Comment by dpfaffenbauer** [comment]
Actually not possible, since Pimcore supports Symfony 3.4 and 4.*

**Comment by fashxp** [comment]
background: we want to support LTS versions of Symfony. 
We will switch as soon as LTS for 3.4 has expired.

**Comment by prugala** [comment]
@fashxp Symfony flex works with version 3.3 and newer. Flex is related with new directory structure so I think should works with components for Symfony ^3.4, ^4.0
https://symfony.com/doc/3.4/setup/flex.html
