### ISSUE TITLE
[Bug]: removing the version from docker-compose.yaml breaks at least docker-compose version 1.23.2

### ISSUE THREAD

**Issue by frithjof** [pimcore/skeleton#94]
### Expected behavior

docker-compose file should not throw an parse error

### Actual behavior

docker-compose up throws an error that file cant be parsed

if i add the 
version: '2.4'
again it works fine

### Steps to reproduce

run docker-compose up probably with older versions

**Comment by frithjof** [comment]
works fine on Docker Compose version v2.5.0
 so it is not really a bug but i am not sure if there are problems with keeping it and being backwards compatible

**Comment by jdreesen** [comment]
Well, `v1.23.2` is really an ancient version (it was released in November 2018). The new spec (which allows omitting the `version` property) should be supported from `v1.27.0` (released in September 2020). Anyway, Docker Compose V1 is deprecated, and you should upgrade to V2, [see the GA announcement](https://www.docker.com/blog/announcing-compose-v2-general-availability/).

**Comment by frithjof** [comment]
yes did that already and you are right about not supporting versions pre 2020
