### ISSUE TITLE
[Improvement]: split up docker-compose.yaml

### ISSUE THREAD

**Issue by passioneight** [pimcore/skeleton#97]
### Improvement description

Currently, the `docker-compose.yaml` contains the complete container configuration. However, when working with different environments running docker (e.g., localhost & staging-server), you may want to have a different configuration.

For example, on localhost I may want to expose the `db` port so I can use my IDE to check the database if needed. On staging, I usually don't want this behaviour. Another example is the `php-fpm-debug` container: I usually only want to start this container locally.

To achieve this, create a `docker-compose.override.yaml` which contains any localhost specific configuration. Now, when starting the containers, the configuration in both files will be merged by default - so no extra work is needed. When starting the containers in any other environment, I can specifically add the `-f docker-compose.yaml - f another-compose-file.yaml` option to merge only these files. 

> If the `-f` option is provided, the `docker-compose.override.yaml` is not used.

This means that exposed ports should be in the `docker-compose.override.yaml` _only_, so that the current behaviour is still default, but it is possible to change it without having to tinker with the originally provided `docker-compose.yaml`.

**Comment by yariksheptykin** [comment]
Thanks for bringing up this discussion @passioneight . I also believe that `docker-compose` could benefit from some redesign.

I suggest we drop `php-fpm-debug` completely and instead parametrize php-fpm service to use either `-debug` or no-debug image flavor. This would also eliminate the need to "balance" between `php-fpm-debug` and `php-fpm` for nginx, which would simplify the config a bit. Triggering xdebug should better be implemented with xdebug means / triggers.

To adjust what ports DB-container binds to per environment it is indeed better to use docker-compose.override.yaml. We can create an example `.override.yaml.dist` in this repo to demonstrate some common customization. However, as this file is supposed to contain individual customizations I don't think we should add this file to the skeleton.

I think that trying to make this docker-compose.yaml staging- or production-ready is a good idea overall. It is, however, dangerous at the same time. This docker-compose.yaml should not be used as is in staging or production environments. Staging should align as close as possible with production. In most of the cases you would not use single-node compose based setups in production. I see the best fit for this docker-compose.yaml file is to set up production-near environment locally.

**Comment by jdreesen** [comment]
> I suggest we drop php-fpm-debug completely and instead parametrize php-fpm service to use either -debug or no-debug image flavor. This would also eliminate the need to "balance" between php-fpm-debug and php-fpm for nginx, which would simplify the config a bit. Triggering xdebug should better be implemented with xdebug means / triggers.

I just created a PR which moves in this direction: #99
